### ISSUE TITLE
.rspec expecting invalid entry

### ISSUE THREAD

**Issue by marysue** [learn-co-curriculum/css-issue-bot-9000#4]
#tasks .completed {
  background-color: #ccc;
  text-decoration: underline;
}

CSS validator indicates background: #ccc; is invalid.  changed to background-color.  CSS Validator validated file properly.  RSpec was looking for background:#ccc which was an invalid entry.

**Comment by Sdcrouse** [comment]
Hi. I'll preface this by saying that I'm a student, not one of the Flatiron engineers. I think the CSS Validator must have been updated since you posted the issue, assuming that you were using the [W3C CSS Validator](http://jigsaw.w3.org/css-validator/#validate_by_input). I'm getting the message "Congratulations! No Error Found." regardless of whether I use `background-color: #ccc;` or `background: #ccc;`.

Hope that helps!

Sdcrouse

**Comment by jenmyers** [comment]
Resolved.
